/**
 * Hypertheme system — visual personality layers beyond color themes.
 *
 * Tech mode defers to the active color theme for all colors.
 * Magic hyperthemes (Arcane, Ethereal, Study, Astral) bring their
 * own complete color palette, overriding the active theme entirely.
 * All hyperthemes control shapes, motion, overlays, and text styling.
 */

export interface HyperthemeConfig {
  id: string;
  label: string;
  description: string;
  icon: string;
  /** Shape / motion / text CSS vars (always applied) */
  cssVars: Record<string, string>;
  /**
   * Full color palette override. When present, these vars are applied
   * as inline styles on <html>, overriding whatever [data-theme] sets.
   * Tech has none — it respects the active color theme.
   */
  colorOverrides?: Record<string, string>;
  suggestedMonoFont: string;
  suggestedSansFont: string;
}

export const HYPERTHEMES: HyperthemeConfig[] = [
  // ── Tech (current default) ──────────────────────────────────────
  // No colorOverrides — respects the active color theme fully.
  {
    id: 'tech',
    label: 'Tech',
    description: 'Sharp edges, scanlines, grid overlay',
    icon: '⬡',
    suggestedMonoFont: 'share-tech-mono',
    suggestedSansFont: 'rajdhani',
    cssVars: {
      '--ht-radius': '2px',
      '--ht-radius-sm': '1px',
      '--ht-radius-lg': '3px',
      '--ht-radius-xl': '4px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '1.5px',
      '--ht-brand-spacing': '3px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1',
      // Structural
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '2px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '16px 28px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '12px 16px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '10px 12px',
      '--ht-item-indicator': '2px',
      '--ht-prose-heading-weight': '700',
      '--ht-body-weight': '500',
    },
  },

  // ── Arcane ──────────────────────────────────────────────────────
  // Deep mystical purple, glowing sigils, cyan & violet accents
  // Matched to lyku's Arcane theme: canvas sigils, vignette, grain
  {
    id: 'arcane',
    label: 'Arcane',
    description: 'Mystical sigils, purple glow, Elder Futhark runes',
    icon: '᚛',
    suggestedMonoFont: 'fira-code',
    suggestedSansFont: 'exo-2',
    cssVars: {
      '--ht-radius': '4px',
      '--ht-radius-sm': '3px',
      '--ht-radius-lg': '6px',
      '--ht-radius-xl': '8px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.8px',
      '--ht-brand-spacing': '2px',
      '--ht-brand-transform': 'none',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.02',
      // Structural — ornate, double borders, wider spacing
      '--ht-border-style': 'double',
      '--ht-border-width': '3px',
      '--ht-msg-border-width': '3px',
      '--ht-msg-border-style': 'double',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '3px',
      '--ht-card-border-style': 'double',
      '--ht-input-border-width': '2px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'dashed',
      '--ht-separator': '3px double var(--border-primary)',
      '--ht-item-padding': '14px 16px',
      '--ht-item-indicator': '3px',
      '--ht-prose-heading-weight': '600',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      // Backgrounds — solid base colors (body uses these)
      '--bg-primary': '#0a0612',
      '--bg-secondary': '#120a1f',
      '--bg-tertiary': '#1a0f2e',
      '--bg-elevated': '#221540',
      '--bg-input': 'rgba(13, 8, 24, 0.9)',
      '--bg-hover': 'rgba(139, 92, 246, 0.12)',
      '--bg-active': 'rgba(139, 92, 246, 0.2)',
      '--bg-selection': 'rgba(139, 92, 246, 0.25)',
      '--bg-code': 'rgba(13, 8, 24, 0.9)',
      '--bg-diff-add': 'rgba(52, 211, 153, 0.08)',
      '--bg-diff-remove': 'rgba(248, 113, 113, 0.08)',
      '--bg-glass': 'rgba(10, 6, 18, 0.55)',
      '--bg-message-user': 'rgba(139, 92, 246, 0.06)',
      '--bg-message-assistant': 'rgba(139, 92, 246, 0.08)',
      // Borders — purple glow
      '--border-primary': 'rgba(139, 92, 246, 0.2)',
      '--border-secondary': 'rgba(139, 92, 246, 0.08)',
      '--border-focus': '#a78bfa',
      '--border-glow': 'rgba(139, 92, 246, 0.4)',
      // Text — soft purple/white
      '--text-primary': '#f0e6ff',
      '--text-secondary': '#a78bfa',
      '--text-tertiary': '#7c3aed',
      '--text-link': '#22d3ee',
      '--text-on-accent': '#0a0612',
      // Accents — cyan + purple + amber
      '--accent-primary': '#22d3ee',
      '--accent-secondary': '#a78bfa',
      '--accent-warning': '#fbbf24',
      '--accent-error': '#f87171',
      '--accent-info': '#22d3ee',
      '--accent-purple': '#a78bfa',
      '--accent-pink': '#ec4899',
      '--accent-gradient': 'linear-gradient(135deg, #7c3aed, #22d3ee)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #6d28d9, #a78bfa, #22d3ee)',
      '--scrollbar-track': 'rgba(139, 92, 246, 0.03)',
      '--scrollbar-thumb': 'rgba(139, 92, 246, 0.2)',
      // Shadows — purple glow
      '--shadow': '0 4px 20px rgba(139, 92, 246, 0.15), 0 0 40px rgba(139, 92, 246, 0.05)',
      '--shadow-lg': '0 10px 30px rgba(139, 92, 246, 0.25)',
      '--shadow-glow': '0 0 15px rgba(139, 92, 246, 0.25), 0 0 40px rgba(139, 92, 246, 0.08)',
      '--shadow-glow-sm': '0 0 8px rgba(139, 92, 246, 0.15)',
      // Syntax — mystical
      '--syn-keyword': '#c084fc',
      '--syn-string': '#34d399',
      '--syn-number': '#fbbf24',
      '--syn-function': '#22d3ee',
      '--syn-comment': '#6b21a8',
      '--syn-type': '#a78bfa',
      '--syn-variable': '#f0e6ff',
      '--syn-operator': '#c084fc',
    },
  },

  // ── Ethereal ───────────────────────────────────────────────────
  // Opalescent — dark pearl interior, seafoam & rose accents, iridescent shimmer
  {
    id: 'ethereal',
    label: 'Ethereal',
    description: 'Soft rounds, floating motes, opalescent shimmer',
    icon: '✦',
    suggestedMonoFont: 'victor-mono',
    suggestedSansFont: 'outfit',
    cssVars: {
      '--ht-radius': '12px',
      '--ht-radius-sm': '8px',
      '--ht-radius-lg': '16px',
      '--ht-radius-xl': '20px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.3px',
      '--ht-brand-spacing': '1.5px',
      '--ht-brand-transform': 'none',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.03',
      // Structural — soft, pillowy, floating, blurred
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '0px',
      '--ht-msg-border-style': 'none',
      '--ht-msg-padding': '20px 30px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '16px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-secondary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '0px',
      '--ht-prose-heading-weight': '500',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      // Backgrounds — cool dark blue-grey, pearl interior
      '--bg-primary': '#08090f',
      '--bg-secondary': '#0c0e16',
      '--bg-tertiary': '#141620',
      '--bg-elevated': '#1c1e2a',
      '--bg-input': '#0a0b12',
      '--bg-hover': 'rgba(125, 211, 192, 0.08)',
      '--bg-active': 'rgba(125, 211, 192, 0.14)',
      '--bg-selection': 'rgba(125, 211, 192, 0.22)',
      '--bg-code': '#0a0b12',
      '--bg-diff-add': 'rgba(125, 211, 192, 0.08)',
      '--bg-diff-remove': 'rgba(232, 160, 184, 0.08)',
      '--bg-glass': 'rgba(8, 9, 15, 0.94)',
      '--bg-message-user': 'rgba(125, 211, 192, 0.04)',
      '--bg-message-assistant': 'rgba(125, 211, 192, 0.06)',
      // Borders — soft teal shimmer
      '--border-primary': 'rgba(125, 211, 192, 0.15)',
      '--border-secondary': 'rgba(125, 211, 192, 0.07)',
      '--border-focus': '#7dd3c0',
      '--border-glow': 'rgba(125, 211, 192, 0.30)',
      // Text — pearlescent cool white
      '--text-primary': '#e0e4ec',
      '--text-secondary': '#8090a8',
      '--text-tertiary': '#506070',
      '--text-link': '#7dd3c0',
      '--text-on-accent': '#08090f',
      // Accents — opalescent: seafoam, rose, gold
      '--accent-primary': '#7dd3c0',
      '--accent-secondary': '#e8a0b8',
      '--accent-warning': '#d4c090',
      '--accent-error': '#e88090',
      '--accent-info': '#90b8d8',
      '--accent-purple': '#b8a0d8',
      '--accent-pink': '#e8a0b8',
      '--accent-gradient': 'linear-gradient(90deg, #7dd3c0, #e8a0b8)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #60c0a8, #7dd3c0, #e8a0b8, #d4c090)',
      '--scrollbar-track': 'rgba(125, 211, 192, 0.03)',
      '--scrollbar-thumb': 'rgba(125, 211, 192, 0.12)',
      // Shadows — soft teal glow
      '--shadow': '0 2px 12px rgba(0, 0, 0, 0.5)',
      '--shadow-lg': '0 8px 32px rgba(0, 0, 0, 0.6)',
      '--shadow-glow': '0 0 14px rgba(125, 211, 192, 0.15)',
      '--shadow-glow-sm': '0 0 7px rgba(125, 211, 192, 0.10)',
      // Syntax — pastel gem palette, each token a different soft hue
      '--syn-keyword': '#e8a0b8',
      '--syn-string': '#7dd3c0',
      '--syn-number': '#90b8d8',
      '--syn-function': '#b8a0d8',
      '--syn-comment': '#506070',
      '--syn-type': '#d4c090',
      '--syn-variable': '#e0e4ec',
      '--syn-operator': '#80c8d0',
    },
  },

  // ── Study ──────────────────────────────────────────────────────
  // The Alchemist's Sanctum — deep plum & charcoal, molten amber,
  // emerald reagents, floating embers, candle smoke, living warmth
  {
    id: 'study',
    label: "Wizard's Study",
    description: 'Floating embers, molten amber, alchemical glow',
    icon: '🜂',
    suggestedMonoFont: 'fira-code',
    suggestedSansFont: 'cinzel',
    cssVars: {
      '--ht-radius': '6px',
      '--ht-radius-sm': '4px',
      '--ht-radius-lg': '8px',
      '--ht-radius-xl': '12px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '1.8px',
      '--ht-brand-spacing': '3px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.01',
      // Structural — refined, warm-edged, subtle depth
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 28px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '3px',
      '--ht-prose-heading-weight': '700',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--rainbow-l': '0.62',
      // Backgrounds — deep plum-charcoal, warm undertone
      '--bg-primary': '#110d14',
      '--bg-secondary': '#16111a',
      '--bg-tertiary': '#1e1724',
      '--bg-elevated': '#271e30',
      '--bg-input': '#0e0b12',
      '--bg-hover': 'rgba(228, 160, 60, 0.08)',
      '--bg-active': 'rgba(228, 160, 60, 0.15)',
      '--bg-selection': 'rgba(228, 160, 60, 0.22)',
      '--bg-code': '#0e0b12',
      '--bg-diff-add': 'rgba(80, 200, 140, 0.10)',
      '--bg-diff-remove': 'rgba(220, 80, 70, 0.10)',
      '--bg-glass': 'rgba(17, 13, 20, 0.92)',
      '--bg-message-user': 'rgba(228, 160, 60, 0.04)',
      '--bg-message-assistant': 'rgba(200, 140, 80, 0.06)',
      // Borders — warm amber glow
      '--border-primary': 'rgba(228, 160, 60, 0.18)',
      '--border-secondary': 'rgba(228, 160, 60, 0.08)',
      '--border-focus': '#e4a03c',
      '--border-glow': 'rgba(228, 160, 60, 0.40)',
      // Text — warm ivory, not muddy
      '--text-primary': '#ede4d4',
      '--text-secondary': '#a89880',
      '--text-tertiary': '#685848',
      '--text-link': '#e4a03c',
      '--text-on-accent': '#110d14',
      // Accents — molten amber, emerald reagent, warm copper
      '--accent-primary': '#e4a03c',
      '--accent-secondary': '#50c88c',
      '--accent-warning': '#e8a830',
      '--accent-error': '#dc5046',
      '--accent-info': '#d4943c',
      '--accent-purple': '#b07cc8',
      '--accent-pink': '#d87070',
      '--accent-gradient': 'linear-gradient(135deg, #d4943c, #e4a03c, #eab860)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #c07828, #e4a03c, #50c88c)',
      '--scrollbar-track': 'rgba(228, 160, 60, 0.03)',
      '--scrollbar-thumb': 'rgba(228, 160, 60, 0.15)',
      // Shadows — warm ember glow
      '--shadow': '0 4px 20px rgba(0, 0, 0, 0.50), 0 0 40px rgba(228, 160, 60, 0.03)',
      '--shadow-lg': '0 8px 36px rgba(0, 0, 0, 0.60), 0 0 60px rgba(228, 160, 60, 0.05)',
      '--shadow-glow': '0 0 14px rgba(228, 160, 60, 0.22), 0 0 40px rgba(228, 160, 60, 0.06)',
      '--shadow-glow-sm': '0 0 8px rgba(228, 160, 60, 0.14)',
      // Syntax — alchemical palette: fire, herb, gold, reagent
      '--syn-keyword': '#d87070',
      '--syn-string': '#50c88c',
      '--syn-number': '#eab860',
      '--syn-function': '#e4a03c',
      '--syn-comment': '#685848',
      '--syn-type': '#b07cc8',
      '--syn-variable': '#ede4d4',
      '--syn-operator': '#d4943c',
    },
  },

  // ── Astral · Twilight ──────────────────────────────────────────
  // Cosmic deep-space blue, celestial blue accent, purple secondary
  // Matched to lyku Cosmic Twilight: nebula gradients, constellation glow
  {
    id: 'astral',
    label: 'Astral · Twilight',
    description: 'Deep space blue, nebula glow, constellations',
    icon: '✧',
    suggestedMonoFont: 'space-mono',
    suggestedSansFont: 'space-grotesk',
    cssVars: {
      '--ht-radius': '3px',
      '--ht-radius-sm': '2px',
      '--ht-radius-lg': '4px',
      '--ht-radius-xl': '6px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '2px',
      '--ht-brand-spacing': '4px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.01',
      // Structural — thin luminous borders, geometric, spacious
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '1px',
      '--ht-prose-heading-weight': '300',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      // Backgrounds — Cosmic Twilight deep space blues
      '--bg-primary': '#020817',
      '--bg-secondary': '#0c1222',
      '--bg-tertiary': '#111827',
      '--bg-elevated': '#1a2236',
      '--bg-input': 'rgba(2, 8, 23, 0.9)',
      '--bg-hover': 'rgba(99, 102, 241, 0.10)',
      '--bg-active': 'rgba(99, 102, 241, 0.18)',
      '--bg-selection': 'rgba(99, 102, 241, 0.25)',
      '--bg-code': 'rgba(2, 8, 23, 0.9)',
      '--bg-diff-add': 'rgba(74, 222, 128, 0.08)',
      '--bg-diff-remove': 'rgba(248, 113, 113, 0.08)',
      '--bg-glass': 'rgba(2, 8, 23, 0.55)',
      '--bg-message-user': 'rgba(96, 165, 250, 0.05)',
      '--bg-message-assistant': 'rgba(96, 165, 250, 0.08)',
      // Borders — indigo glow
      '--border-primary': 'rgba(99, 102, 241, 0.15)',
      '--border-secondary': 'rgba(99, 102, 241, 0.07)',
      '--border-focus': '#60a5fa',
      '--border-glow': 'rgba(96, 165, 250, 0.40)',
      // Text — light indigo
      '--text-primary': '#e0e7ff',
      '--text-secondary': '#94a3b8',
      '--text-tertiary': '#64748b',
      '--text-link': '#60a5fa',
      '--text-on-accent': '#020817',
      // Accents — celestial blue, purple, gold
      '--accent-primary': '#60a5fa',
      '--accent-secondary': '#a78bfa',
      '--accent-warning': '#fbbf24',
      '--accent-error': '#f87171',
      '--accent-info': '#60a5fa',
      '--accent-purple': '#a78bfa',
      '--accent-pink': '#f472b6',
      '--accent-gradient': 'linear-gradient(90deg, #60a5fa, #a78bfa)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #3b82f6, #60a5fa, #a78bfa)',
      '--scrollbar-track': 'rgba(99, 102, 241, 0.03)',
      '--scrollbar-thumb': 'rgba(99, 102, 241, 0.15)',
      // Shadows — indigo/blue cosmic glow
      '--shadow': '0 4px 20px rgba(99, 102, 241, 0.10), 0 0 60px rgba(59, 130, 246, 0.05)',
      '--shadow-lg': '0 10px 30px rgba(99, 102, 241, 0.20)',
      '--shadow-glow': '0 0 15px rgba(96, 165, 250, 0.20), 0 0 40px rgba(96, 165, 250, 0.06)',
      '--shadow-glow-sm': '0 0 8px rgba(96, 165, 250, 0.12)',
      // Syntax — celestial
      '--syn-keyword': '#f472b6',
      '--syn-string': '#4ade80',
      '--syn-number': '#a78bfa',
      '--syn-function': '#60a5fa',
      '--syn-comment': '#64748b',
      '--syn-type': '#fbbf24',
      '--syn-variable': '#e0e7ff',
      '--syn-operator': '#93c5fd',
    },
  },

  // ── Astral · Midnight ────────────────────────────────────────
  // Cosmic OLED pure black, same accent palette, stronger glow
  // Matched to lyku Cosmic Midnight: no nebula, maximum contrast
  {
    id: 'astral-midnight',
    label: 'Astral · Midnight',
    description: 'OLED black, bright stars, maximum contrast',
    icon: '★',
    suggestedMonoFont: 'space-mono',
    suggestedSansFont: 'space-grotesk',
    cssVars: {
      '--ht-radius': '3px',
      '--ht-radius-sm': '2px',
      '--ht-radius-lg': '4px',
      '--ht-radius-xl': '6px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '2px',
      '--ht-brand-spacing': '4px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.01',
      // Structural — same geometric layout as Twilight
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '1px',
      '--ht-prose-heading-weight': '300',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      // Backgrounds — pure OLED black
      '--bg-primary': '#000000',
      '--bg-secondary': '#050508',
      '--bg-tertiary': '#0a0a0f',
      '--bg-elevated': '#101018',
      '--bg-input': 'rgba(0, 0, 0, 0.9)',
      '--bg-hover': 'rgba(99, 102, 241, 0.08)',
      '--bg-active': 'rgba(99, 102, 241, 0.16)',
      '--bg-selection': 'rgba(99, 102, 241, 0.22)',
      '--bg-code': 'rgba(0, 0, 0, 0.9)',
      '--bg-diff-add': 'rgba(74, 222, 128, 0.08)',
      '--bg-diff-remove': 'rgba(248, 113, 113, 0.08)',
      '--bg-glass': 'rgba(0, 0, 0, 0.55)',
      '--bg-message-user': 'rgba(59, 130, 246, 0.06)',
      '--bg-message-assistant': 'rgba(59, 130, 246, 0.06)',
      // Borders — subtle indigo on black
      '--border-primary': 'rgba(99, 102, 241, 0.12)',
      '--border-secondary': 'rgba(99, 102, 241, 0.06)',
      '--border-focus': '#60a5fa',
      '--border-glow': 'rgba(96, 165, 250, 0.50)',
      // Text — high contrast on pure black
      '--text-primary': '#f0f4ff',
      '--text-secondary': '#8b95a8',
      '--text-tertiary': '#5a6478',
      '--text-link': '#60a5fa',
      '--text-on-accent': '#000000',
      // Accents — same celestial palette, more prominent on black
      '--accent-primary': '#60a5fa',
      '--accent-secondary': '#a78bfa',
      '--accent-warning': '#fbbf24',
      '--accent-error': '#f87171',
      '--accent-info': '#60a5fa',
      '--accent-purple': '#a78bfa',
      '--accent-pink': '#f472b6',
      '--accent-gradient': 'linear-gradient(90deg, #60a5fa, #a78bfa)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #3b82f6, #60a5fa, #a78bfa)',
      '--scrollbar-track': 'rgba(99, 102, 241, 0.02)',
      '--scrollbar-thumb': 'rgba(99, 102, 241, 0.12)',
      // Shadows — stronger glow on pure black
      '--shadow': '0 4px 20px rgba(0, 0, 0, 0.80), 0 0 60px rgba(59, 130, 246, 0.03)',
      '--shadow-lg': '0 10px 30px rgba(0, 0, 0, 0.90)',
      '--shadow-glow': '0 0 20px rgba(96, 165, 250, 0.25), 0 0 50px rgba(96, 165, 250, 0.08)',
      '--shadow-glow-sm': '0 0 10px rgba(96, 165, 250, 0.18)',
      // Syntax — same celestial palette
      '--syn-keyword': '#f472b6',
      '--syn-string': '#4ade80',
      '--syn-number': '#a78bfa',
      '--syn-function': '#60a5fa',
      '--syn-comment': '#5a6478',
      '--syn-type': '#fbbf24',
      '--syn-variable': '#f0f4ff',
      '--syn-operator': '#93c5fd',
    },
  },

  // ── Goth ───────────────────────────────────────────────────────
  // Pure void black, dried blood crimson, aged bone text,
  // coffin-nail sharp edges, and a permanent bad bitch energy
  {
    id: 'goth',
    label: 'Redrum',
    description: 'Void black, dried blood, aged bone',
    icon: '🖤',
    suggestedMonoFont: 'fira-code',
    suggestedSansFont: 'cinzel',
    cssVars: {
      '--ht-radius': '0px',
      '--ht-radius-sm': '0px',
      '--ht-radius-lg': '1px',
      '--ht-radius-xl': '2px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '2.5px',
      '--ht-brand-spacing': '4px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '200ms',
      '--ht-hover-scale': '1',
      // Structural — razor-sharp edges, heavy black lace borders
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 28px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '2px',
      '--ht-prose-heading-weight': '700',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--rainbow-l': '0.45',
      // Backgrounds — pure void black, no color cast
      '--bg-primary': '#080808',
      '--bg-secondary': '#0e0e0e',
      '--bg-tertiary': '#161616',
      '--bg-elevated': '#1e1e1e',
      '--bg-input': 'rgba(5, 5, 5, 0.98)',
      '--bg-hover': 'rgba(139, 0, 0, 0.08)',
      '--bg-active': 'rgba(139, 0, 0, 0.16)',
      '--bg-selection': 'rgba(139, 0, 0, 0.28)',
      '--bg-code': 'rgba(5, 5, 5, 0.98)',
      '--bg-diff-add': 'rgba(100, 0, 0, 0.15)',
      '--bg-diff-remove': 'rgba(180, 0, 0, 0.12)',
      '--bg-glass': 'rgba(8, 8, 8, 0.92)',
      '--bg-message-user': 'rgba(120, 0, 0, 0.05)',
      '--bg-message-assistant': 'rgba(100, 0, 0, 0.07)',
      // Borders — dried blood, barely-there
      '--border-primary': 'rgba(180, 10, 10, 0.25)',
      '--border-secondary': 'rgba(180, 10, 10, 0.10)',
      '--border-focus': '#8b0000',
      '--border-glow': 'rgba(160, 0, 0, 0.50)',
      // Text — aged bone, ash secondary
      '--text-primary': '#d8cfc4',
      '--text-secondary': '#7a706a',
      '--text-tertiary': '#4a4240',
      '--text-link': '#a03030',
      '--text-on-accent': '#d8cfc4',
      // Accents — deep crimson, dried blood, shadow purple
      '--accent-primary': '#8b0000',
      '--accent-secondary': '#5a0a0a',
      '--accent-warning': '#7a3a00',
      '--accent-error': '#cc1a1a',
      '--accent-info': '#4a3a5a',
      '--accent-purple': '#4a2060',
      '--accent-pink': '#6a1030',
      '--accent-gradient': 'linear-gradient(135deg, #3a0000, #8b0000)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #200000, #8b0000, #3a1040)',
      '--scrollbar-track': 'rgba(100, 0, 0, 0.04)',
      '--scrollbar-thumb': 'rgba(139, 0, 0, 0.25)',
      // Shadows — pure void with blood seeping at the edges
      '--shadow': '0 4px 20px rgba(0, 0, 0, 0.9), 0 0 40px rgba(100, 0, 0, 0.06)',
      '--shadow-lg': '0 10px 36px rgba(0, 0, 0, 0.95), 0 0 60px rgba(100, 0, 0, 0.08)',
      '--shadow-glow': '0 0 18px rgba(139, 0, 0, 0.28), 0 0 50px rgba(139, 0, 0, 0.08)',
      '--shadow-glow-sm': '0 0 10px rgba(139, 0, 0, 0.18)',
      // Syntax — dried blood, dark earth, shadow
      '--syn-keyword': '#cc2222',
      '--syn-string': '#7a4a2a',
      '--syn-number': '#8b4513',
      '--syn-function': '#a03030',
      '--syn-comment': '#4a4240',
      '--syn-type': '#6a2040',
      '--syn-variable': '#d8cfc4',
      '--syn-operator': '#8b0000',
    },
  },
];

/** Find a hypertheme config by ID */
export function findHypertheme(id: string): HyperthemeConfig | undefined {
  return HYPERTHEMES.find((ht) => ht.id === id);
}

/** Get the default hypertheme */
export function getDefaultHypertheme(): HyperthemeConfig {
  return HYPERTHEMES[0]; // tech
}
