/**
 * Hypertheme system — visual personality layers beyond color themes.
 *
 * Tech mode defers to the active color theme for all colors.
 * Magic hyperthemes (Arcane, Ethereal, Study, Astral) bring their
 * own complete color palette, overriding the active theme entirely.
 * All hyperthemes control shapes, motion, overlays, and text styling.
 */

export interface HyperthemeConfig {
  id: string;
  label: string;
  description: string;
  icon: string;
  /** Shape / motion / text CSS vars (always applied) */
  cssVars: Record<string, string>;
  /**
   * Full color palette override. When present, these vars are applied
   * as inline styles on <html>, overriding whatever [data-theme] sets.
   * Tech has none — it respects the active color theme.
   */
  colorOverrides?: Record<string, string>;
  suggestedMonoFont: string;
  suggestedSansFont: string;
}

export const HYPERTHEMES: HyperthemeConfig[] = [
  // ── Tech (current default) ──────────────────────────────────────
  // No colorOverrides — respects the active color theme fully.
  {
    id: 'tech',
    label: 'Tech',
    description: 'Sharp edges, scanlines, grid overlay',
    icon: '⬡',
    suggestedMonoFont: 'share-tech-mono',
    suggestedSansFont: 'rajdhani',
    cssVars: {
      '--ht-radius': '2px',
      '--ht-radius-sm': '1px',
      '--ht-radius-lg': '3px',
      '--ht-radius-xl': '4px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '1.5px',
      '--ht-brand-spacing': '3px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '150ms',
      '--ht-hover-scale': '1',
      // Structural
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '2px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '16px 28px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '12px 16px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '10px 12px',
      '--ht-item-indicator': '2px',
      '--ht-prose-heading-weight': '700',
      '--ht-body-weight': '500',
    },
  },

  // ── Arcane ──────────────────────────────────────────────────────
  // Deep mystical purple, glowing sigils, cyan & violet accents
  // Matched to lyku's Arcane theme: canvas sigils, vignette, grain
  {
    id: 'arcane',
    label: 'Arcane',
    description: 'Mystical sigils, purple glow, Elder Futhark runes',
    icon: '᚛',
    suggestedMonoFont: 'fira-code',
    suggestedSansFont: 'exo-2',
    cssVars: {
      '--ht-radius': '4px',
      '--ht-radius-sm': '3px',
      '--ht-radius-lg': '6px',
      '--ht-radius-xl': '8px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.8px',
      '--ht-brand-spacing': '2px',
      '--ht-brand-transform': 'none',
      '--ht-transition-speed': '250ms',
      '--ht-hover-scale': '1.02',
      // Structural — ornate, double borders, wider spacing
      '--ht-border-style': 'double',
      '--ht-border-width': '3px',
      '--ht-msg-border-width': '3px',
      '--ht-msg-border-style': 'double',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '3px',
      '--ht-card-border-style': 'double',
      '--ht-input-border-width': '2px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'dashed',
      '--ht-separator': '3px double var(--border-primary)',
      '--ht-item-padding': '14px 16px',
      '--ht-item-indicator': '3px',
      '--ht-prose-heading-weight': '600',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      // Backgrounds — solid base colors (body uses these)
      '--bg-primary': '#0a0612',
      '--bg-secondary': '#120a1f',
      '--bg-tertiary': '#1a0f2e',
      '--bg-elevated': '#221540',
      '--bg-input': 'rgba(13, 8, 24, 0.9)',
      '--bg-hover': 'rgba(139, 92, 246, 0.12)',
      '--bg-active': 'rgba(139, 92, 246, 0.2)',
      '--bg-selection': 'rgba(139, 92, 246, 0.25)',
      '--bg-code': 'rgba(13, 8, 24, 0.9)',
      '--bg-diff-add': 'rgba(52, 211, 153, 0.08)',
      '--bg-diff-remove': 'rgba(248, 113, 113, 0.08)',
      '--bg-glass': 'rgba(10, 6, 18, 0.55)',
      '--bg-message-user': 'rgba(139, 92, 246, 0.06)',
      '--bg-message-assistant': 'rgba(139, 92, 246, 0.08)',
      // Borders — purple glow
      '--border-primary': 'rgba(139, 92, 246, 0.2)',
      '--border-secondary': 'rgba(139, 92, 246, 0.08)',
      '--border-focus': '#a78bfa',
      '--border-glow': 'rgba(139, 92, 246, 0.4)',
      // Text — soft purple/white
      '--text-primary': '#f0e6ff',
      '--text-secondary': '#a78bfa',
      '--text-tertiary': '#7c3aed',
      '--text-link': '#22d3ee',
      '--text-on-accent': '#0a0612',
      // Accents — cyan + purple + amber
      '--accent-primary': '#22d3ee',
      '--accent-secondary': '#a78bfa',
      '--accent-warning': '#fbbf24',
      '--accent-error': '#f87171',
      '--accent-info': '#22d3ee',
      '--accent-purple': '#a78bfa',
      '--accent-pink': '#ec4899',
      '--accent-gradient': 'linear-gradient(135deg, #7c3aed, #22d3ee)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #6d28d9, #a78bfa, #22d3ee)',
      '--scrollbar-track': 'rgba(139, 92, 246, 0.03)',
      '--scrollbar-thumb': 'rgba(139, 92, 246, 0.2)',
      // Shadows — purple glow
      '--shadow': '0 4px 20px rgba(139, 92, 246, 0.15), 0 0 40px rgba(139, 92, 246, 0.05)',
      '--shadow-lg': '0 10px 30px rgba(139, 92, 246, 0.25)',
      '--shadow-glow': '0 0 15px rgba(139, 92, 246, 0.25), 0 0 40px rgba(139, 92, 246, 0.08)',
      '--shadow-glow-sm': '0 0 8px rgba(139, 92, 246, 0.15)',
      // Syntax — mystical
      '--syn-keyword': '#c084fc',
      '--syn-string': '#34d399',
      '--syn-number': '#fbbf24',
      '--syn-function': '#22d3ee',
      '--syn-comment': '#6b21a8',
      '--syn-type': '#a78bfa',
      '--syn-variable': '#f0e6ff',
      '--syn-operator': '#c084fc',
    },
  },

  // ── Ethereal ───────────────────────────────────────────────────
  // Deep indigo-violet, iridescent pastel accents, dreamy
  {
    id: 'ethereal',
    label: 'Ethereal',
    description: 'Soft rounds, floating particles, iridescent glow',
    icon: '✦',
    suggestedMonoFont: 'victor-mono',
    suggestedSansFont: 'outfit',
    cssVars: {
      '--ht-radius': '12px',
      '--ht-radius-sm': '8px',
      '--ht-radius-lg': '16px',
      '--ht-radius-xl': '20px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.3px',
      '--ht-brand-spacing': '1.5px',
      '--ht-brand-transform': 'none',
      '--ht-transition-speed': '350ms',
      '--ht-hover-scale': '1.03',
      // Structural — soft, pillowy, floating, blurred
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '0px',
      '--ht-msg-border-style': 'none',
      '--ht-msg-padding': '20px 30px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '16px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-secondary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '0px',
      '--ht-prose-heading-weight': '500',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--bg-primary': '#0c0814',
      '--bg-secondary': '#100c18',
      '--bg-tertiary': '#18122a',
      '--bg-elevated': '#201838',
      '--bg-input': '#0e0a16',
      '--bg-hover': 'rgba(160, 120, 240, 0.08)',
      '--bg-active': 'rgba(160, 120, 240, 0.14)',
      '--bg-selection': 'rgba(160, 120, 240, 0.22)',
      '--bg-code': '#0e0a16',
      '--bg-diff-add': 'rgba(120, 220, 180, 0.08)',
      '--bg-diff-remove': 'rgba(240, 100, 140, 0.08)',
      '--bg-glass': 'rgba(12, 8, 20, 0.94)',
      '--bg-message-user': 'rgba(160, 120, 240, 0.04)',
      '--bg-message-assistant': 'rgba(160, 120, 240, 0.06)',
      '--border-primary': 'rgba(160, 120, 240, 0.15)',
      '--border-secondary': 'rgba(160, 120, 240, 0.07)',
      '--border-focus': '#a078f0',
      '--border-glow': 'rgba(160, 120, 240, 0.3)',
      '--text-primary': '#d8d0f0',
      '--text-secondary': '#8880b0',
      '--text-tertiary': '#504878',
      '--text-link': '#a088f0',
      '--text-on-accent': '#0c0814',
      '--accent-primary': '#a078f0',
      '--accent-secondary': '#78dcb4',
      '--accent-warning': '#e0b860',
      '--accent-error': '#f06888',
      '--accent-info': '#80b0f0',
      '--accent-purple': '#b080f0',
      '--accent-pink': '#e080c0',
      '--accent-gradient': 'linear-gradient(90deg, #a078f0, #e080c0)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #8060d0, #a078f0, #e080c0)',
      '--scrollbar-track': 'rgba(160, 120, 240, 0.03)',
      '--scrollbar-thumb': 'rgba(160, 120, 240, 0.12)',
      '--shadow': '0 2px 12px rgba(0, 0, 0, 0.5)',
      '--shadow-lg': '0 8px 32px rgba(0, 0, 0, 0.6)',
      '--shadow-glow': '0 0 14px rgba(160, 120, 240, 0.15)',
      '--shadow-glow-sm': '0 0 7px rgba(160, 120, 240, 0.1)',
      '--syn-keyword': '#e080c0',
      '--syn-string': '#78dcb4',
      '--syn-number': '#80b0f0',
      '--syn-function': '#a078f0',
      '--syn-comment': '#504878',
      '--syn-type': '#e0b860',
      '--syn-variable': '#d8d0f0',
      '--syn-operator': '#a088f0',
    },
  },

  // ── Study ──────────────────────────────────────────────────────
  // Warm parchment cream, deep brown/sepia, candlelit warmth
  {
    id: 'study',
    label: "Wizard's Study",
    description: 'Warm parchment, candlelight, leather & ink',
    icon: '🕯',
    suggestedMonoFont: 'courier-prime',
    suggestedSansFont: 'crimson-pro',
    cssVars: {
      '--ht-radius': '3px',
      '--ht-radius-sm': '2px',
      '--ht-radius-lg': '4px',
      '--ht-radius-xl': '6px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.2px',
      '--ht-brand-spacing': '0.5px',
      '--ht-brand-transform': 'capitalize',
      '--ht-transition-speed': '200ms',
      '--ht-hover-scale': '1',
      // Structural — thick borders, inset/embossed, book-spine feel
      '--ht-border-style': 'solid',
      '--ht-border-width': '2px',
      '--ht-msg-border-width': '4px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '24px 36px',
      '--ht-card-border-width': '2px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '2px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '2px solid var(--border-primary)',
      '--ht-item-padding': '14px 18px',
      '--ht-item-indicator': '4px',
      '--ht-prose-heading-weight': '600',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--rainbow-l': '0.58',
      '--bg-primary': '#1a100a',
      '--bg-secondary': '#1e1410',
      '--bg-tertiary': '#291c14',
      '--bg-elevated': '#33241a',
      '--bg-input': '#16100a',
      '--bg-hover': 'rgba(218, 165, 50, 0.07)',
      '--bg-active': 'rgba(218, 165, 50, 0.14)',
      '--bg-selection': 'rgba(218, 165, 50, 0.22)',
      '--bg-code': '#16100a',
      '--bg-diff-add': 'rgba(120, 180, 80, 0.10)',
      '--bg-diff-remove': 'rgba(200, 60, 50, 0.10)',
      '--bg-glass': 'rgba(26, 16, 10, 0.95)',
      '--bg-message-user': 'rgba(218, 165, 50, 0.05)',
      '--bg-message-assistant': 'rgba(160, 120, 60, 0.07)',
      '--border-primary': 'rgba(180, 130, 60, 0.20)',
      '--border-secondary': 'rgba(180, 130, 60, 0.10)',
      '--border-focus': '#daa532',
      '--border-glow': 'rgba(218, 165, 50, 0.35)',
      '--text-primary': '#e8dcc4',
      '--text-secondary': '#a08c6c',
      '--text-tertiary': '#6a5840',
      '--text-link': '#daa532',
      '--text-on-accent': '#1a100a',
      '--accent-primary': '#daa532',
      '--accent-secondary': '#8aba55',
      '--accent-warning': '#e8a830',
      '--accent-error': '#cc4433',
      '--accent-info': '#c49038',
      '--accent-purple': '#b07848',
      '--accent-pink': '#c06848',
      '--accent-gradient': 'linear-gradient(90deg, #c49038, #daa532)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #a07028, #daa532, #e8c050)',
      '--scrollbar-track': 'rgba(180, 130, 60, 0.04)',
      '--scrollbar-thumb': 'rgba(180, 130, 60, 0.18)',
      '--shadow': '0 2px 14px rgba(0, 0, 0, 0.55)',
      '--shadow-lg': '0 8px 36px rgba(0, 0, 0, 0.65)',
      '--shadow-glow': '0 0 12px rgba(218, 165, 50, 0.18)',
      '--shadow-glow-sm': '0 0 6px rgba(218, 165, 50, 0.12)',
      '--syn-keyword': '#cc4433',
      '--syn-string': '#8aba55',
      '--syn-number': '#daa532',
      '--syn-function': '#c49038',
      '--syn-comment': '#6a5840',
      '--syn-type': '#e8a830',
      '--syn-variable': '#e8dcc4',
      '--syn-operator': '#c49038',
    },
  },

  // ── Astral ─────────────────────────────────────────────────────
  // Deep space blue-black, cool silver-blue, starlight accents
  {
    id: 'astral',
    label: 'Astral',
    description: 'Deep space, starfields, constellation light',
    icon: '✧',
    suggestedMonoFont: 'space-mono',
    suggestedSansFont: 'space-grotesk',
    cssVars: {
      '--ht-radius': '3px',
      '--ht-radius-sm': '2px',
      '--ht-radius-lg': '4px',
      '--ht-radius-xl': '6px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '2px',
      '--ht-brand-spacing': '4px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '400ms',
      '--ht-hover-scale': '1.01',
      // Structural — thin luminous borders, geometric, spacious
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '1px',
      '--ht-prose-heading-weight': '300',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--bg-primary': '#060810',
      '--bg-secondary': '#080a14',
      '--bg-tertiary': '#0e1220',
      '--bg-elevated': '#14182c',
      '--bg-input': '#070910',
      '--bg-hover': 'rgba(140, 160, 220, 0.07)',
      '--bg-active': 'rgba(140, 160, 220, 0.13)',
      '--bg-selection': 'rgba(140, 160, 220, 0.22)',
      '--bg-code': '#070910',
      '--bg-diff-add': 'rgba(100, 200, 160, 0.08)',
      '--bg-diff-remove': 'rgba(200, 100, 120, 0.08)',
      '--bg-glass': 'rgba(6, 8, 16, 0.95)',
      '--bg-message-user': 'rgba(140, 160, 220, 0.04)',
      '--bg-message-assistant': 'rgba(140, 160, 220, 0.06)',
      '--border-primary': 'rgba(140, 160, 220, 0.14)',
      '--border-secondary': 'rgba(140, 160, 220, 0.07)',
      '--border-focus': '#8ca0dc',
      '--border-glow': 'rgba(140, 160, 220, 0.30)',
      '--text-primary': '#c8d0e8',
      '--text-secondary': '#6878a0',
      '--text-tertiary': '#3c4868',
      '--text-link': '#8ca0e0',
      '--text-on-accent': '#060810',
      '--accent-primary': '#8ca0dc',
      '--accent-secondary': '#68c8a0',
      '--accent-warning': '#d0b060',
      '--accent-error': '#d06878',
      '--accent-info': '#80a8e0',
      '--accent-purple': '#a088d0',
      '--accent-pink': '#c080b0',
      '--accent-gradient': 'linear-gradient(90deg, #8ca0dc, #a088d0)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #6080c0, #8ca0dc, #a088d0)',
      '--scrollbar-track': 'rgba(140, 160, 220, 0.02)',
      '--scrollbar-thumb': 'rgba(140, 160, 220, 0.12)',
      '--shadow': '0 2px 12px rgba(0, 0, 0, 0.6)',
      '--shadow-lg': '0 8px 32px rgba(0, 0, 0, 0.7)',
      '--shadow-glow': '0 0 15px rgba(140, 160, 220, 0.12)',
      '--shadow-glow-sm': '0 0 8px rgba(140, 160, 220, 0.08)',
      '--syn-keyword': '#d06878',
      '--syn-string': '#68c8a0',
      '--syn-number': '#a088d0',
      '--syn-function': '#8ca0dc',
      '--syn-comment': '#3c4868',
      '--syn-type': '#d0b060',
      '--syn-variable': '#c8d0e8',
      '--syn-operator': '#80a8e0',
    },
  },
];

/** Find a hypertheme config by ID */
export function findHypertheme(id: string): HyperthemeConfig | undefined {
  return HYPERTHEMES.find((ht) => ht.id === id);
}

/** Get the default hypertheme */
export function getDefaultHypertheme(): HyperthemeConfig {
  return HYPERTHEMES[0]; // tech
}
