/**
 * Unified Theme System
 *
 * Each theme is a complete visual package: colors, shapes, motion, effects.
 *
 * Standard themes (Dark, Monokai, etc.) use the Tech visual style with
 * colors from CSS [data-theme] selectors. Their structural vars match Tech.
 *
 * Immersive themes (Arcane, Ethereal, Study, etc.) bring their own
 * complete color palette AND unique structural styling, ambient effects,
 * suggested fonts, and optional commentary personality.
 */

export interface ThemeConfig {
  id: string;
  label: string;
  description: string;
  /** SVG path data for the icon (rendered in a 24×24 viewBox). Immersive themes only. */
  icon?: string;
  /** 'standard' = colors from CSS, Tech shapes. 'immersive' = full custom experience. */
  category: 'standard' | 'immersive';
  /** Base type for CSS fallback: 'dark' or 'light' */
  type: 'dark' | 'light';
  /** Shape / motion / text CSS vars (--ht-*) */
  cssVars: Record<string, string>;
  /**
   * Full color palette override. Applied as inline styles on <html>,
   * overriding whatever [data-theme] sets. Only used by immersive themes.
   */
  colorOverrides?: Record<string, string>;
  suggestedMonoFont: string;
  suggestedSansFont: string;
  /**
   * Optional suggested commentary personality for this theme.
   * When the user switches to this theme, the commentary panel
   * can auto-activate this personality for a more immersive experience.
   */
  suggestedPersonality?: string;
}

// ── Tech structural CSS vars (shared by all standard themes) ─────────────
const TECH_CSS_VARS: Record<string, string> = {
  '--ht-radius': '2px',
  '--ht-radius-sm': '1px',
  '--ht-radius-lg': '3px',
  '--ht-radius-xl': '4px',
  '--ht-label-transform': 'uppercase',
  '--ht-label-spacing': '1.5px',
  '--ht-brand-spacing': '3px',
  '--ht-brand-transform': 'uppercase',
  '--ht-transition-speed': '125ms',
  '--ht-hover-scale': '1',
  '--ht-border-style': 'solid',
  '--ht-border-width': '1px',
  '--ht-msg-border-width': '2px',
  '--ht-msg-border-style': 'solid',
  '--ht-msg-padding': '16px 28px',
  '--ht-card-border-width': '1px',
  '--ht-card-border-style': 'solid',
  '--ht-input-border-width': '1px',
  '--ht-input-border-style': 'solid',
  '--ht-input-padding': '12px 16px',
  '--ht-badge-border-style': 'solid',
  '--ht-separator': '1px solid var(--border-primary)',
  '--ht-item-padding': '10px 12px',
  '--ht-item-indicator': '2px',
  '--ht-prose-heading-weight': '700',
  '--ht-body-weight': '500',
};

/** Create a standard theme entry (Tech visual style + CSS color palette) */
function std(id: string, label: string, type: 'dark' | 'light' = 'dark'): ThemeConfig {
  return {
    id,
    label,
    description: '',
    category: 'standard',
    type,
    cssVars: { ...TECH_CSS_VARS },
    suggestedMonoFont: 'share-tech-mono',
    suggestedSansFont: 'rajdhani',
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// All themes — standard color palettes first, then immersive experiences
// ═══════════════════════════════════════════════════════════════════════════

export const THEMES: ThemeConfig[] = [
  // ── Standard Themes (Tech visual style + color palette from CSS) ───────
  std('dark', 'Dark'),
  std('light', 'Light', 'light'),
  std('dark-colorblind', 'Dark (Colorblind)'),
  std('light-colorblind', 'Light (Colorblind)', 'light'),
  std('dark-ansi', 'Dark (ANSI)'),
  std('light-ansi', 'Light (ANSI)', 'light'),
  std('monokai', 'Monokai'),
  std('dracula', 'Dracula'),
  std('nord', 'Nord'),
  std('gruvbox-dark', 'Gruvbox Dark'),
  std('gruvbox-light', 'Gruvbox Light', 'light'),
  std('solarized-dark', 'Solarized Dark'),
  std('solarized-light', 'Solarized Light', 'light'),
  std('catppuccin-mocha', 'Catppuccin Mocha'),
  std('catppuccin-latte', 'Catppuccin Latte', 'light'),
  std('tokyo-night', 'Tokyo Night'),
  std('rose-pine', 'Rosé Pine'),
  std('rose-pine-dawn', 'Rosé Pine Dawn', 'light'),
  std('synthwave', "Synthwave '84"),
  std('github-dark', 'GitHub Dark'),
  std('github-light', 'GitHub Light', 'light'),
  std('one-dark', 'One Dark'),
  std('everforest', 'Everforest'),
  std('sakura-light', 'Sakura Light', 'light'),
  std('sakura', 'Sakura Dark'),
  std('high-contrast', 'High Contrast Dark'),
  std('high-contrast-light', 'High Contrast Light', 'light'),

  // ── Immersive Themes (complete visual experience) ──────────────────────

  // ── Arcane ──────────────────────────────────────────────────────
  // Deep mystical purple, glowing sigils, cyan & violet accents
  {
    id: 'arcane',
    label: 'Arcane',
    description: 'Mystical sigils, purple glow, Elder Futhark runes',
    icon: 'M12 2l3 7h7l-5.5 4.5 2 7L12 16l-6.5 4.5 2-7L2 9h7l3-7z',
    category: 'immersive',
    type: 'dark',
    suggestedMonoFont: 'fira-code',
    suggestedSansFont: 'exo-2',
    cssVars: {
      '--ht-radius': '4px',
      '--ht-radius-sm': '3px',
      '--ht-radius-lg': '6px',
      '--ht-radius-xl': '8px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.8px',
      '--ht-brand-spacing': '2px',
      '--ht-brand-transform': 'none',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.02',
      '--ht-border-style': 'double',
      '--ht-border-width': '3px',
      '--ht-msg-border-width': '3px',
      '--ht-msg-border-style': 'double',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '3px',
      '--ht-card-border-style': 'double',
      '--ht-input-border-width': '2px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'dashed',
      '--ht-separator': '3px double var(--border-primary)',
      '--ht-item-padding': '14px 16px',
      '--ht-item-indicator': '3px',
      '--ht-prose-heading-weight': '600',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--bg-primary': '#0a0612',
      '--bg-secondary': '#120a1f',
      '--bg-tertiary': '#1a0f2e',
      '--bg-elevated': '#221540',
      '--bg-input': 'rgba(13, 8, 24, 0.9)',
      '--bg-hover': 'rgba(139, 92, 246, 0.12)',
      '--bg-active': 'rgba(139, 92, 246, 0.2)',
      '--bg-selection': 'rgba(139, 92, 246, 0.25)',
      '--bg-code': 'rgba(13, 8, 24, 0.9)',
      '--bg-diff-add': 'rgba(52, 211, 153, 0.08)',
      '--bg-diff-remove': 'rgba(248, 113, 113, 0.08)',
      '--bg-glass': 'rgba(10, 6, 18, 0.55)',
      '--bg-message-user': 'rgba(139, 92, 246, 0.06)',
      '--bg-message-assistant': 'rgba(139, 92, 246, 0.08)',
      '--border-primary': 'rgba(139, 92, 246, 0.2)',
      '--border-secondary': 'rgba(139, 92, 246, 0.08)',
      '--border-focus': '#a78bfa',
      '--border-glow': 'rgba(139, 92, 246, 0.4)',
      '--text-primary': '#f0e6ff',
      '--text-secondary': '#a78bfa',
      '--text-tertiary': '#7c3aed',
      '--text-link': '#22d3ee',
      '--text-on-accent': '#0a0612',
      '--accent-primary': '#22d3ee',
      '--accent-secondary': '#a78bfa',
      '--accent-warning': '#fbbf24',
      '--accent-error': '#f87171',
      '--accent-info': '#22d3ee',
      '--accent-purple': '#a78bfa',
      '--accent-pink': '#ec4899',
      '--accent-gradient': 'linear-gradient(135deg, #7c3aed, #22d3ee)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #6d28d9, #a78bfa, #22d3ee)',
      '--scrollbar-track': 'rgba(139, 92, 246, 0.03)',
      '--scrollbar-thumb': 'rgba(139, 92, 246, 0.2)',
      '--shadow': '0 4px 20px rgba(139, 92, 246, 0.15), 0 0 40px rgba(139, 92, 246, 0.05)',
      '--shadow-lg': '0 10px 30px rgba(139, 92, 246, 0.25)',
      '--shadow-glow': '0 0 15px rgba(139, 92, 246, 0.25), 0 0 40px rgba(139, 92, 246, 0.08)',
      '--shadow-glow-sm': '0 0 8px rgba(139, 92, 246, 0.15)',
      '--syn-keyword': '#c084fc',
      '--syn-string': '#34d399',
      '--syn-number': '#fbbf24',
      '--syn-function': '#22d3ee',
      '--syn-comment': '#6b21a8',
      '--syn-type': '#a78bfa',
      '--syn-variable': '#f0e6ff',
      '--syn-operator': '#c084fc',
    },
  },

  // ── Ethereal ───────────────────────────────────────────────────
  // Opalescent — dark pearl interior, seafoam & rose accents, iridescent shimmer
  {
    id: 'ethereal',
    label: 'Ethereal',
    description: 'Soft rounds, floating motes, opalescent shimmer',
    icon: 'M12 3c-1.2 3-3.8 5.6-9 6 5.2.4 7.8 3 9 6 1.2-3 3.8-5.6 9-6-5.2-.4-7.8-3-9-6z',
    category: 'immersive',
    type: 'dark',
    suggestedMonoFont: 'victor-mono',
    suggestedSansFont: 'outfit',
    cssVars: {
      '--ht-radius': '12px',
      '--ht-radius-sm': '8px',
      '--ht-radius-lg': '16px',
      '--ht-radius-xl': '20px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.3px',
      '--ht-brand-spacing': '1.5px',
      '--ht-brand-transform': 'none',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.03',
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '0px',
      '--ht-msg-border-style': 'none',
      '--ht-msg-padding': '20px 30px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '16px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-secondary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '0px',
      '--ht-prose-heading-weight': '500',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--bg-primary': '#08090f',
      '--bg-secondary': '#0c0e16',
      '--bg-tertiary': '#141620',
      '--bg-elevated': '#1c1e2a',
      '--bg-input': '#0a0b12',
      '--bg-hover': 'rgba(125, 211, 192, 0.08)',
      '--bg-active': 'rgba(125, 211, 192, 0.14)',
      '--bg-selection': 'rgba(125, 211, 192, 0.22)',
      '--bg-code': '#0a0b12',
      '--bg-diff-add': 'rgba(125, 211, 192, 0.08)',
      '--bg-diff-remove': 'rgba(232, 160, 184, 0.08)',
      '--bg-glass': 'rgba(8, 9, 15, 0.94)',
      '--bg-message-user': 'rgba(125, 211, 192, 0.04)',
      '--bg-message-assistant': 'rgba(125, 211, 192, 0.06)',
      '--border-primary': 'rgba(125, 211, 192, 0.15)',
      '--border-secondary': 'rgba(125, 211, 192, 0.07)',
      '--border-focus': '#7dd3c0',
      '--border-glow': 'rgba(125, 211, 192, 0.30)',
      '--text-primary': '#e0e4ec',
      '--text-secondary': '#8090a8',
      '--text-tertiary': '#506070',
      '--text-link': '#7dd3c0',
      '--text-on-accent': '#08090f',
      '--accent-primary': '#7dd3c0',
      '--accent-secondary': '#e8a0b8',
      '--accent-warning': '#d4c090',
      '--accent-error': '#e88090',
      '--accent-info': '#90b8d8',
      '--accent-purple': '#b8a0d8',
      '--accent-pink': '#e8a0b8',
      '--accent-gradient': 'linear-gradient(90deg, #7dd3c0, #e8a0b8)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #60c0a8, #7dd3c0, #e8a0b8, #d4c090)',
      '--scrollbar-track': 'rgba(125, 211, 192, 0.03)',
      '--scrollbar-thumb': 'rgba(125, 211, 192, 0.12)',
      '--shadow': '0 2px 12px rgba(0, 0, 0, 0.5)',
      '--shadow-lg': '0 8px 32px rgba(0, 0, 0, 0.6)',
      '--shadow-glow': '0 0 14px rgba(125, 211, 192, 0.15)',
      '--shadow-glow-sm': '0 0 7px rgba(125, 211, 192, 0.10)',
      '--syn-keyword': '#e8a0b8',
      '--syn-string': '#7dd3c0',
      '--syn-number': '#90b8d8',
      '--syn-function': '#b8a0d8',
      '--syn-comment': '#506070',
      '--syn-type': '#d4c090',
      '--syn-variable': '#e0e4ec',
      '--syn-operator': '#80c8d0',
    },
  },

  // ── Wizard's Study ─────────────────────────────────────────────
  // The Alchemist's Sanctum — deep plum & charcoal, molten amber,
  // emerald reagents, floating embers, candle smoke, living warmth
  {
    id: 'study',
    label: "Wizard's Study",
    description: 'Floating embers, molten amber, alchemical glow',
    icon: 'M12 2c-4 6-8 9.5-8 13a8 8 0 0 0 16 0c0-3.5-4-7-8-13z',
    category: 'immersive',
    type: 'dark',
    suggestedMonoFont: 'fira-code',
    suggestedSansFont: 'cinzel',
    suggestedPersonality: 'wizard',
    cssVars: {
      '--ht-radius': '6px',
      '--ht-radius-sm': '4px',
      '--ht-radius-lg': '8px',
      '--ht-radius-xl': '12px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '1.8px',
      '--ht-brand-spacing': '3px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.01',
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 28px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '3px',
      '--ht-prose-heading-weight': '700',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--rainbow-l': '0.62',
      '--bg-primary': '#110d14',
      '--bg-secondary': '#16111a',
      '--bg-tertiary': '#1e1724',
      '--bg-elevated': '#271e30',
      '--bg-input': '#0e0b12',
      '--bg-hover': 'rgba(228, 160, 60, 0.08)',
      '--bg-active': 'rgba(228, 160, 60, 0.15)',
      '--bg-selection': 'rgba(228, 160, 60, 0.22)',
      '--bg-code': '#0e0b12',
      '--bg-diff-add': 'rgba(80, 200, 140, 0.10)',
      '--bg-diff-remove': 'rgba(220, 80, 70, 0.10)',
      '--bg-glass': 'rgba(17, 13, 20, 0.92)',
      '--bg-message-user': 'rgba(228, 160, 60, 0.04)',
      '--bg-message-assistant': 'rgba(200, 140, 80, 0.06)',
      '--border-primary': 'rgba(228, 160, 60, 0.18)',
      '--border-secondary': 'rgba(228, 160, 60, 0.08)',
      '--border-focus': '#e4a03c',
      '--border-glow': 'rgba(228, 160, 60, 0.40)',
      '--text-primary': '#ede4d4',
      '--text-secondary': '#a89880',
      '--text-tertiary': '#685848',
      '--text-link': '#e4a03c',
      '--text-on-accent': '#110d14',
      '--accent-primary': '#e4a03c',
      '--accent-secondary': '#50c88c',
      '--accent-warning': '#e8a830',
      '--accent-error': '#dc5046',
      '--accent-info': '#d4943c',
      '--accent-purple': '#b07cc8',
      '--accent-pink': '#d87070',
      '--accent-gradient': 'linear-gradient(135deg, #d4943c, #e4a03c, #eab860)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #c07828, #e4a03c, #50c88c)',
      '--scrollbar-track': 'rgba(228, 160, 60, 0.03)',
      '--scrollbar-thumb': 'rgba(228, 160, 60, 0.15)',
      '--shadow': '0 4px 20px rgba(0, 0, 0, 0.50), 0 0 40px rgba(228, 160, 60, 0.03)',
      '--shadow-lg': '0 8px 36px rgba(0, 0, 0, 0.60), 0 0 60px rgba(228, 160, 60, 0.05)',
      '--shadow-glow': '0 0 14px rgba(228, 160, 60, 0.22), 0 0 40px rgba(228, 160, 60, 0.06)',
      '--shadow-glow-sm': '0 0 8px rgba(228, 160, 60, 0.14)',
      '--syn-keyword': '#d87070',
      '--syn-string': '#50c88c',
      '--syn-number': '#eab860',
      '--syn-function': '#e4a03c',
      '--syn-comment': '#685848',
      '--syn-type': '#b07cc8',
      '--syn-variable': '#ede4d4',
      '--syn-operator': '#d4943c',
    },
  },

  // ── Astral · Twilight ──────────────────────────────────────────
  // Cosmic deep-space blue, celestial blue accent, purple secondary
  {
    id: 'astral',
    label: 'Astral · Twilight',
    description: 'Deep space blue, nebula glow, constellations',
    icon: 'M12 2l2.4 7.4H22l-6.2 4.5 2.4 7.4L12 16.8l-6.2 4.5 2.4-7.4L2 9.4h7.6L12 2z M5 3l1 2M19 3l-1 2M3 12l2 .5M21 12l-2 .5',
    category: 'immersive',
    type: 'dark',
    suggestedMonoFont: 'space-mono',
    suggestedSansFont: 'space-grotesk',
    cssVars: {
      '--ht-radius': '3px',
      '--ht-radius-sm': '2px',
      '--ht-radius-lg': '4px',
      '--ht-radius-xl': '6px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '2px',
      '--ht-brand-spacing': '4px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.01',
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '1px',
      '--ht-prose-heading-weight': '300',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--bg-primary': '#020817',
      '--bg-secondary': '#0c1222',
      '--bg-tertiary': '#111827',
      '--bg-elevated': '#1a2236',
      '--bg-input': 'rgba(2, 8, 23, 0.9)',
      '--bg-hover': 'rgba(99, 102, 241, 0.10)',
      '--bg-active': 'rgba(99, 102, 241, 0.18)',
      '--bg-selection': 'rgba(99, 102, 241, 0.25)',
      '--bg-code': 'rgba(2, 8, 23, 0.9)',
      '--bg-diff-add': 'rgba(74, 222, 128, 0.08)',
      '--bg-diff-remove': 'rgba(248, 113, 113, 0.08)',
      '--bg-glass': 'rgba(2, 8, 23, 0.55)',
      '--bg-message-user': 'rgba(96, 165, 250, 0.05)',
      '--bg-message-assistant': 'rgba(96, 165, 250, 0.08)',
      '--border-primary': 'rgba(99, 102, 241, 0.15)',
      '--border-secondary': 'rgba(99, 102, 241, 0.07)',
      '--border-focus': '#60a5fa',
      '--border-glow': 'rgba(96, 165, 250, 0.40)',
      '--text-primary': '#e0e7ff',
      '--text-secondary': '#94a3b8',
      '--text-tertiary': '#64748b',
      '--text-link': '#60a5fa',
      '--text-on-accent': '#020817',
      '--accent-primary': '#60a5fa',
      '--accent-secondary': '#a78bfa',
      '--accent-warning': '#fbbf24',
      '--accent-error': '#f87171',
      '--accent-info': '#60a5fa',
      '--accent-purple': '#a78bfa',
      '--accent-pink': '#f472b6',
      '--accent-gradient': 'linear-gradient(90deg, #60a5fa, #a78bfa)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #3b82f6, #60a5fa, #a78bfa)',
      '--scrollbar-track': 'rgba(99, 102, 241, 0.03)',
      '--scrollbar-thumb': 'rgba(99, 102, 241, 0.15)',
      '--shadow': '0 4px 20px rgba(99, 102, 241, 0.10), 0 0 60px rgba(59, 130, 246, 0.05)',
      '--shadow-lg': '0 10px 30px rgba(99, 102, 241, 0.20)',
      '--shadow-glow': '0 0 15px rgba(96, 165, 250, 0.20), 0 0 40px rgba(96, 165, 250, 0.06)',
      '--shadow-glow-sm': '0 0 8px rgba(96, 165, 250, 0.12)',
      '--syn-keyword': '#f472b6',
      '--syn-string': '#4ade80',
      '--syn-number': '#a78bfa',
      '--syn-function': '#60a5fa',
      '--syn-comment': '#64748b',
      '--syn-type': '#fbbf24',
      '--syn-variable': '#e0e7ff',
      '--syn-operator': '#93c5fd',
    },
  },

  // ── Astral · Midnight ────────────────────────────────────────
  // Cosmic OLED pure black, same accent palette, stronger glow
  {
    id: 'astral-midnight',
    label: 'Astral · Midnight',
    description: 'OLED black, bright stars, maximum contrast',
    icon: 'M12 2l2.4 7.4H22l-6.2 4.5 2.4 7.4L12 16.8l-6.2 4.5 2.4-7.4L2 9.4h7.6L12 2z',
    category: 'immersive',
    type: 'dark',
    suggestedMonoFont: 'space-mono',
    suggestedSansFont: 'space-grotesk',
    cssVars: {
      '--ht-radius': '3px',
      '--ht-radius-sm': '2px',
      '--ht-radius-lg': '4px',
      '--ht-radius-xl': '6px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '2px',
      '--ht-brand-spacing': '4px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '125ms',
      '--ht-hover-scale': '1.01',
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 32px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 20px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '1px',
      '--ht-prose-heading-weight': '300',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#050508',
      '--bg-tertiary': '#0a0a0f',
      '--bg-elevated': '#101018',
      '--bg-input': 'rgba(0, 0, 0, 0.9)',
      '--bg-hover': 'rgba(99, 102, 241, 0.08)',
      '--bg-active': 'rgba(99, 102, 241, 0.16)',
      '--bg-selection': 'rgba(99, 102, 241, 0.22)',
      '--bg-code': 'rgba(0, 0, 0, 0.9)',
      '--bg-diff-add': 'rgba(74, 222, 128, 0.08)',
      '--bg-diff-remove': 'rgba(248, 113, 113, 0.08)',
      '--bg-glass': 'rgba(0, 0, 0, 0.55)',
      '--bg-message-user': 'rgba(59, 130, 246, 0.06)',
      '--bg-message-assistant': 'rgba(59, 130, 246, 0.06)',
      '--border-primary': 'rgba(99, 102, 241, 0.12)',
      '--border-secondary': 'rgba(99, 102, 241, 0.06)',
      '--border-focus': '#60a5fa',
      '--border-glow': 'rgba(96, 165, 250, 0.50)',
      '--text-primary': '#f0f4ff',
      '--text-secondary': '#8b95a8',
      '--text-tertiary': '#5a6478',
      '--text-link': '#60a5fa',
      '--text-on-accent': '#000000',
      '--accent-primary': '#60a5fa',
      '--accent-secondary': '#a78bfa',
      '--accent-warning': '#fbbf24',
      '--accent-error': '#f87171',
      '--accent-info': '#60a5fa',
      '--accent-purple': '#a78bfa',
      '--accent-pink': '#f472b6',
      '--accent-gradient': 'linear-gradient(90deg, #60a5fa, #a78bfa)',
      '--accent-gradient-vivid': 'linear-gradient(90deg, #3b82f6, #60a5fa, #a78bfa)',
      '--scrollbar-track': 'rgba(99, 102, 241, 0.02)',
      '--scrollbar-thumb': 'rgba(99, 102, 241, 0.12)',
      '--shadow': '0 4px 20px rgba(0, 0, 0, 0.80), 0 0 60px rgba(59, 130, 246, 0.03)',
      '--shadow-lg': '0 10px 30px rgba(0, 0, 0, 0.90)',
      '--shadow-glow': '0 0 20px rgba(96, 165, 250, 0.25), 0 0 50px rgba(96, 165, 250, 0.08)',
      '--shadow-glow-sm': '0 0 10px rgba(96, 165, 250, 0.18)',
      '--syn-keyword': '#f472b6',
      '--syn-string': '#4ade80',
      '--syn-number': '#a78bfa',
      '--syn-function': '#60a5fa',
      '--syn-comment': '#5a6478',
      '--syn-type': '#fbbf24',
      '--syn-variable': '#f0f4ff',
      '--syn-operator': '#93c5fd',
    },
  },

  // ── Redrum (Goth) ──────────────────────────────────────────────
  // Pure void black, dried blood crimson, aged bone text
  {
    id: 'goth',
    label: 'Redrum',
    description: 'Void black, dried blood, aged bone',
    icon: 'M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78z',
    category: 'immersive',
    type: 'dark',
    suggestedMonoFont: 'fira-code',
    suggestedSansFont: 'cinzel',
    cssVars: {
      '--ht-radius': '0px',
      '--ht-radius-sm': '0px',
      '--ht-radius-lg': '1px',
      '--ht-radius-xl': '2px',
      '--ht-label-transform': 'uppercase',
      '--ht-label-spacing': '2.5px',
      '--ht-brand-spacing': '4px',
      '--ht-brand-transform': 'uppercase',
      '--ht-transition-speed': '200ms',
      '--ht-hover-scale': '1',
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 28px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '2px',
      '--ht-prose-heading-weight': '700',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--rainbow-l': '0.45',
      '--bg-primary': '#080808',
      '--bg-secondary': '#0e0e0e',
      '--bg-tertiary': '#161616',
      '--bg-elevated': '#1e1e1e',
      '--bg-input': 'rgba(5, 5, 5, 0.98)',
      '--bg-hover': 'rgba(139, 0, 0, 0.08)',
      '--bg-active': 'rgba(139, 0, 0, 0.16)',
      '--bg-selection': 'rgba(139, 0, 0, 0.28)',
      '--bg-code': 'rgba(5, 5, 5, 0.98)',
      '--bg-diff-add': 'rgba(100, 0, 0, 0.15)',
      '--bg-diff-remove': 'rgba(180, 0, 0, 0.12)',
      '--bg-glass': 'rgba(8, 8, 8, 0.92)',
      '--bg-message-user': 'rgba(120, 0, 0, 0.05)',
      '--bg-message-assistant': 'rgba(100, 0, 0, 0.07)',
      '--border-primary': 'rgba(180, 10, 10, 0.25)',
      '--border-secondary': 'rgba(180, 10, 10, 0.10)',
      '--border-focus': '#8b0000',
      '--border-glow': 'rgba(160, 0, 0, 0.50)',
      '--text-primary': '#d8cfc4',
      '--text-secondary': '#7a706a',
      '--text-tertiary': '#4a4240',
      '--text-link': '#a03030',
      '--text-on-accent': '#d8cfc4',
      '--accent-primary': '#8b0000',
      '--accent-secondary': '#5a0a0a',
      '--accent-warning': '#7a3a00',
      '--accent-error': '#cc1a1a',
      '--accent-info': '#4a3a5a',
      '--accent-purple': '#4a2060',
      '--accent-pink': '#6a1030',
      '--accent-gradient': 'linear-gradient(135deg, #3a0000, #8b0000)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #200000, #8b0000, #3a1040)',
      '--scrollbar-track': 'rgba(100, 0, 0, 0.04)',
      '--scrollbar-thumb': 'rgba(139, 0, 0, 0.25)',
      '--shadow': '0 4px 20px rgba(0, 0, 0, 0.9), 0 0 40px rgba(100, 0, 0, 0.06)',
      '--shadow-lg': '0 10px 36px rgba(0, 0, 0, 0.95), 0 0 60px rgba(100, 0, 0, 0.08)',
      '--shadow-glow': '0 0 18px rgba(139, 0, 0, 0.28), 0 0 50px rgba(139, 0, 0, 0.08)',
      '--shadow-glow-sm': '0 0 10px rgba(139, 0, 0, 0.18)',
      '--syn-keyword': '#cc2222',
      '--syn-string': '#7a4a2a',
      '--syn-number': '#8b4513',
      '--syn-function': '#a03030',
      '--syn-comment': '#4a4240',
      '--syn-type': '#6a2040',
      '--syn-variable': '#d8cfc4',
      '--syn-operator': '#8b0000',
    },
  },

  // ── Magic Forest ────────────────────────────────────────────────
  // Deep enchanted woodland — mossy greens, dappled sunlight gold,
  // bioluminescent mushroom glow, ancient bark browns, fairy dust motes.
  {
    id: 'magic-forest',
    label: 'Magic Forest',
    description: 'Enchanted woods, bioluminescent glow, fairy dust',
    icon: 'M17 8c.7-1 1-2.2 1-3.5C18 2 16 2 16 2s0 2-2.5 3.5S9 8 9 8s-1.5 2-1.5 4.5c0 3 2 5.5 4.5 5.5 1 0 2-.3 2.8-.8M7 16c-1 1.5-1 3.5-1 3.5s2 0 3.5-1.5M12 22v-4',
    category: 'immersive',
    type: 'dark',
    suggestedMonoFont: 'victor-mono',
    suggestedSansFont: 'cormorant-garamond',
    cssVars: {
      '--ht-radius': '10px',
      '--ht-radius-sm': '6px',
      '--ht-radius-lg': '14px',
      '--ht-radius-xl': '18px',
      '--ht-label-transform': 'none',
      '--ht-label-spacing': '0.5px',
      '--ht-brand-spacing': '1.5px',
      '--ht-brand-transform': 'none',
      '--ht-transition-speed': '200ms',
      '--ht-hover-scale': '1.02',
      '--ht-border-style': 'solid',
      '--ht-border-width': '1px',
      '--ht-msg-border-width': '1px',
      '--ht-msg-border-style': 'solid',
      '--ht-msg-padding': '20px 28px',
      '--ht-card-border-width': '1px',
      '--ht-card-border-style': 'solid',
      '--ht-input-border-width': '1px',
      '--ht-input-border-style': 'solid',
      '--ht-input-padding': '14px 18px',
      '--ht-badge-border-style': 'solid',
      '--ht-separator': '1px solid var(--border-primary)',
      '--ht-item-padding': '12px 16px',
      '--ht-item-indicator': '2px',
      '--ht-prose-heading-weight': '600',
      '--ht-body-weight': '400',
    },
    colorOverrides: {
      '--rainbow-l': '0.55',
      '--bg-primary': '#070d08',
      '--bg-secondary': '#0c140e',
      '--bg-tertiary': '#121c15',
      '--bg-elevated': '#1a2a1e',
      '--bg-input': 'rgba(7, 13, 8, 0.95)',
      '--bg-hover': 'rgba(80, 200, 120, 0.08)',
      '--bg-active': 'rgba(80, 200, 120, 0.14)',
      '--bg-selection': 'rgba(80, 200, 120, 0.20)',
      '--bg-code': 'rgba(7, 13, 8, 0.95)',
      '--bg-diff-add': 'rgba(80, 200, 120, 0.10)',
      '--bg-diff-remove': 'rgba(220, 100, 80, 0.10)',
      '--bg-glass': 'rgba(7, 13, 8, 0.88)',
      '--bg-message-user': 'rgba(80, 200, 120, 0.04)',
      '--bg-message-assistant': 'rgba(160, 210, 120, 0.05)',
      '--border-primary': 'rgba(80, 200, 120, 0.18)',
      '--border-secondary': 'rgba(80, 200, 120, 0.08)',
      '--border-focus': '#50c878',
      '--border-glow': 'rgba(80, 200, 120, 0.35)',
      '--text-primary': '#d8e8d0',
      '--text-secondary': '#88a880',
      '--text-tertiary': '#506850',
      '--text-link': '#7dd8a0',
      '--text-on-accent': '#070d08',
      '--accent-primary': '#50c878',
      '--accent-secondary': '#d4a840',
      '--accent-warning': '#e8b830',
      '--accent-error': '#dc6050',
      '--accent-info': '#60c8b0',
      '--accent-purple': '#a070c8',
      '--accent-pink': '#c870a0',
      '--accent-gradient': 'linear-gradient(135deg, #50c878, #d4a840)',
      '--accent-gradient-vivid': 'linear-gradient(135deg, #38b060, #50c878, #60c8b0, #d4a840)',
      '--scrollbar-track': 'rgba(80, 200, 120, 0.03)',
      '--scrollbar-thumb': 'rgba(80, 200, 120, 0.18)',
      '--shadow': '0 4px 20px rgba(0, 0, 0, 0.50), 0 0 40px rgba(80, 200, 120, 0.04)',
      '--shadow-lg': '0 8px 36px rgba(0, 0, 0, 0.60), 0 0 60px rgba(80, 200, 120, 0.06)',
      '--shadow-glow': '0 0 14px rgba(80, 200, 120, 0.20), 0 0 40px rgba(80, 200, 120, 0.06)',
      '--shadow-glow-sm': '0 0 8px rgba(80, 200, 120, 0.12)',
      '--syn-keyword': '#c870a0',
      '--syn-string': '#50c878',
      '--syn-number': '#d4a840',
      '--syn-function': '#7dd8a0',
      '--syn-comment': '#506850',
      '--syn-type': '#a070c8',
      '--syn-variable': '#d8e8d0',
      '--syn-operator': '#60c8b0',
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// Lookup helpers
// ═══════════════════════════════════════════════════════════════════════════

/** IDs of all immersive themes (used to determine visual style for data-hypertheme) */
const IMMERSIVE_IDS = new Set(THEMES.filter((t) => t.category === 'immersive').map((t) => t.id));

/** Find a theme config by ID */
export function findTheme(id: string): ThemeConfig | undefined {
  return THEMES.find((t) => t.id === id);
}

/** Get the default theme */
export function getDefaultTheme(): ThemeConfig {
  return THEMES[0]; // dark
}

/**
 * Get the visual style ID for a given theme ID.
 * Standard themes use 'tech' (the default structural style).
 * Immersive themes use their own ID as the visual style.
 * This maps to the `data-hypertheme` attribute on <html>.
 */
export function getVisualStyle(themeId: string): string {
  return IMMERSIVE_IDS.has(themeId) ? themeId : 'tech';
}

/**
 * Check whether a theme is immersive (has its own visual style + colors).
 */
export function isImmersiveTheme(themeId: string): boolean {
  return IMMERSIVE_IDS.has(themeId);
}

// ═══════════════════════════════════════════════════════════════════════════
// Backward compatibility — re-export old names for gradual migration
// ═══════════════════════════════════════════════════════════════════════════

/** @deprecated Use ThemeConfig instead */
export type HyperthemeConfig = ThemeConfig;
/** @deprecated Use THEMES instead */
export const HYPERTHEMES = THEMES.filter((t) => t.category === 'immersive');
/** @deprecated Use findTheme instead */
export function findHypertheme(id: string): ThemeConfig | undefined {
  return findTheme(id);
}
/** @deprecated Use getDefaultTheme instead */
export function getDefaultHypertheme(): ThemeConfig {
  return getDefaultTheme();
}
